### ISSUE TITLE
Any recommended devices?

### ISSUE THREAD

**Issue by Huizerd** [PSBPOSAS/dji-asdk-to-python#20]
* DJI Android SDK to Python version: 0.1.0
* Python version: 3.8.5
* Operating System: Android 8.1.0 / Ubuntu 20.04

### Description

Trying examples

### What I Did

Installed the `.rpk` on the phone (Nexus 6P), connected to Mavic Mini, it shows a still image (so some data is getting through) but it's not being updated. Accepted all the required permissions. I took the displayed IP and inserted it into the battery and state examples, but neither worked.

### Questions

- Are there any phones you recommend/that you know work?
- Are there any steps I missed?

**Comment by cartovarc** [comment]
I don't think Ubuntu or Python can give you problems. Those states are not implemented in version 0.1.0. Our example tests have only been done on android 9.0, with an ODROID N2 4GB RAM SBC. You can check release examples at https://github.com/PSBPOSAS/dji-asdk-to-python/tree/cf3e56691524624314a28f5ebc6f3f59cbd4d8cb

**Comment by Huizerd** [comment]
Nice, that gives something to go on. Thanks!
