### ISSUE TITLE
Using the SDK with DJI Mavic 2 Pro drone

### ISSUE THREAD

**Issue by msanchezc** [PSBPOSAS/dji-asdk-to-python#9]
* DJI Android SDK to Python version: 0.1.0
* Python version: 3.8
* Operating System: Raspberry Pi OS August 2020

### Description

We are MindLabs, a small team based in Chile developing a solution for autonomous drone operation. We found this project while searching for open-source software to control DJI drones without the need to build an Android app with the DJI Mobile SDK. What we need is a little walkthrough to understand how to use your software in order to integrate it with our solution and, eventually, being able to contribute.

### What We Did

We looked at the examples directory, but we are not sure how to setup the Android device to connect with this software. Looking at the code, we found that it uses the `APP_IP` environment variable to connect to a device on port `11111`. Do we need to install something on the Android device?

Your help would be really appreciated.

**Comment by cartovarc** [comment]
Hi! for testing you need install dji-asdk-to-python android app on your device. You can download it here:

https://github.com/PSBPOSAS/dji-asdk-to-python/releases/tag/v0.1.0

We hope to upload the app soon to the play store.

We are open to any request for improvement, bug reports, etc. Thank you very much!

**Comment by msanchezc** [comment]
Thank you very much!

We will begin testing right now, we are really excited about this project!
